solution for cards on main
js-tasks-ru/htmlcss-20211125_alex-d pull request #10
Opened 2021-12-23 06:23 UTC by AlexDayanov

2021-12-23 06:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-23 07:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-23 19:45 UTC, GSemikozov requested changes

2021-12-23 19:45 UTC, GSemikozov commented on components/card/card.css
> +.cards__grid {
в блоке card могут быть стили только для этого блока, а cards - это уже другой блок

2021-12-24 13:23 UTC, GSemikozov approved these changes

2021-12-24 13:23 UTC, merged