Dz1 button 2
js-tasks-ru/htmlcss-20211125_alex-d pull request #14
Opened 2022-01-07 14:32 UTC by AlexDayanov

2022-01-07 14:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-07 20:30 UTC, GSemikozov requested changes

2022-01-07 20:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +
не хватает всех общих стилей - паддинги, бордеры, бордер-радиусы, стили для текста)

2022-01-07 20:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_medium {
все отсюда можно перенести в .button - в нашем дизайне кнопки только одного размера

2022-01-07 20:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background-color 200ms ease-in-out;
транзишн тоже можно сразу на на .button, без :hover

2022-01-08 09:46 UTC, AlexDayanov commented on 03-lection1/01-button/button.css
> +
перенес из button_medium

2022-01-08 09:47 UTC, AlexDayanov commented on 03-lection1/01-button/button.css
> +.button_medium {
удалил  button_medium

2022-01-08 09:47 UTC, AlexDayanov commented on 03-lection1/01-button/button.css
> +    transition: opacity 200ms ease-in-out, background-color 200ms ease-in-out;
перевесил на .button

2022-01-08 09:58 UTC, AlexDayanov commented on 03-lection1/01-button/button.css
> +.button_medium {
Но тогда разметка противоречит бэм: в блоке появились размеры

2022-01-08 10:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-12 19:52 UTC, GSemikozov approved these changes

2022-01-12 19:52 UTC, merged