solution for Dz1-layout-2
js-tasks-ru/htmlcss-20211125_alex-d pull request #7
Opened 2021-12-11 15:58 UTC by AlexDayanov

2021-12-11 15:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 18:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-13 15:39 UTC, GSemikozov requested changes

2021-12-13 15:39 UTC, GSemikozov commented on components/header/header.css
> +    margin: 96px 0 77px 160px;
слева точно нужен 160?

2021-12-14 09:16 UTC, AlexDayanov commented on components/header/header.css
> +    margin: 96px 0 77px 160px;
по прототипу 160

2021-12-14 09:17 UTC, AlexDayanov commented on components/header/header.css
> +    margin: 96px 0 77px 160px;
ну, или 10rem )

2021-12-14 19:34 UTC, GSemikozov commented on components/header/header.css
> +    margin: 96px 0 77px 160px;
на десктопе 1440? десктопы бывают разные) 
у нас есть контейнер по которому контент и выравнивается, а отступы будут высчитываться автоматом, в зависимости от ширины экрана (у контейнера, напомню, margin: 0 auto)

2021-12-15 04:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-15 05:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 10:24 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-16 10:27 UTC, GSemikozov approved these changes

2021-12-16 10:27 UTC, merged